Entwicklung BdiAgentV2 inklusive "task/naviInterface"
h1Modeling/ss22_fp_mapc_gruppe3 pull request #51
Opened 2022-05-20 15:26 UTC by melinda5

Ich benutze derzeit eigene "Subdesire" -Klassen, da in einigen schon Actions ( in localExplore, GoGoalZone, DigFree, GoRoleZone, GoDispenser, DodgeClear ) ermittelt werden. Wenn möglich möchte ich mich natürlich später an eure Klassen anpassen und diese benutzen.

2022-05-21 13:10 UTC, h1Modeling requested changes
Bitte auf alle Fälle den DesireHandler wieder aktivieren.

Ich habe deinen Agenten ein paar Sekunden laufen lassen. In dieser Zeit hat er knappe 1000 Threads erstellt und wieder zerstört. Da die Erstellung von Threads auch einen gewissen Overhead mit sich bringt, frage ich mich schon ob du mit dem Threadkonzept die erwartete Performance bekommst. Da müsste man wahrscheinlich mal ein paar Vergleichstests machen.

Die Einbindung des Navis finde ich aktuell schwierig. Die Kapselung der Map sollte auf alle Fälle nicht aufgegeben werden. Falls du direkt auf den Maps arbeiten willst, solltest du generell nicht mit dem Navi arbeiten.

Ich hatte auch eine Null-Pointer Exception in einem Thread konnte diese aber nicht reproduzieren (gab auch keine weitern Information außer Exception in Thread xy)

2022-05-22 08:23 UTC, melinda5 commented
Ich hab jetzt alle Korrekturen eingefügt.

2022-05-22 11:06 UTC, h1Modeling approved these changes

2022-05-22 11:09 UTC, h1Modeling commented
Bei den Reachables hast du mich glaube ich falsch verstanden. Mir ging es drum, dass sie nicht als innere Records definiert werden wenn sie public sind. Habe einen commit gemacht und sie in einem eigenem Namespace in reguläre Records geändert.

2022-05-22 11:12 UTC, merged